UPD: improves daemon startup
Tries to do a better job at determining whether the daemon startup succeeded or not.

diff --git a/maestro-agent/src/main/scripts/maestro-agent-service b/maestro-agent/src/main/scripts/maestro-agent-service
--- a/maestro-agent/src/main/scripts/maestro-agent-service
+++ b/maestro-agent/src/main/scripts/maestro-agent-service
@@ -22,12 +22,40 @@ fi
 
 source "$installdir"/config/maestro-agent-service.conf
 
+RED="\e[0;31m"
+GREEN="\e[0;32m"
+RESET="\e[0m"
+
+function esuccess() {
+    echo -e "$GREEN OK$RESET"
+}
+
+function eerror() {
+    echo -e "$RED failed$RESET ($@)"
+}
+
 function start() {
+    echo -en "Starting the daemon: "
     nohup "$installdir"/bin/maestro-agent -m "$MAESTRO_BROKER" -l "$MAESTRO_LOG_DIR" $@ > /dev/null 2> /dev/null &
+    if [ $? -ne 0 ] ; then
+        eerror "failed to daemonize the Maestro agent"
+        exit 1
+    fi
+
     sleep 2s
+    proc_count=0
     for pid in $(ps -ef | grep -i maestro-agent | grep java | grep -v worker-agent | grep -v grep | awk ' { print $2 } ') ; do
-        echo "Maestro agent started $pid"
+        if [ $proc_count -eq 0 ] ; then
+            esuccess
+        fi
+
+        echo -e "Maestro agent started:$GREEN $pid $RESET"
+        ((proc_count++))
     done
+
+    if [ $proc_count -eq 0 ] ; then
+        eerror "Maestro agent did not start successfully"
+    fi
 }
 
 function stop() {
diff --git a/maestro-exporter/src/main/scripts/maestro-exporter-service b/maestro-exporter/src/main/scripts/maestro-exporter-service
--- a/maestro-exporter/src/main/scripts/maestro-exporter-service
+++ b/maestro-exporter/src/main/scripts/maestro-exporter-service
@@ -22,11 +22,35 @@ fi
 
 source "$installdir"/config/maestro-exporter-service.conf
 
+RED="\e[0;31m"
+GREEN="\e[0;32m"
+RESET="\e[0m"
+
+function esuccess() {
+    echo -e "$GREEN OK$RESET"
+}
+
+function eerror() {
+    echo -e "$RED failed$RESET ($@)"
+}
+
 function start() {
+    echo -en "Starting the daemon: "
     nohup "$installdir"/bin/maestro-exporter -m "$MAESTRO_BROKER" $@ > /dev/null 2> /dev/null &
+    if [ $? -ne 0 ] ; then
+        eerror "failed to daemonize the Maestro agent"
+        exit 1
+    fi
+
     sleep 2s
+    proc_count=0
     for pid in $(ps -ef | grep -i maestro-exporter | grep java | grep -v bash | grep -v exporter-service | grep -v grep | awk ' { print $2 } ') ; do
-        echo "Maestro exporter started $pid"
+        if [ $proc_count -eq 0 ] ; then
+            esuccess
+        fi
+
+        echo -e "Maestro exporter started:$GREEN $pid $RESET"
+        ((proc_count++))
     done
 }
 
diff --git a/maestro-inspector/src/main/scripts/maestro-inspector-service b/maestro-inspector/src/main/scripts/maestro-inspector-service
--- a/maestro-inspector/src/main/scripts/maestro-inspector-service
+++ b/maestro-inspector/src/main/scripts/maestro-inspector-service
@@ -22,13 +22,38 @@ fi
 
 source "$installdir"/config/maestro-inspector-service.conf
 
-function start() {
+RED="\e[0;31m"
+GREEN="\e[0;32m"
+RESET="\e[0m"
 
+function esuccess() {
+    echo -e "$GREEN OK$RESET"
+}
+
+function eerror() {
+    echo -e "$RED failed$RESET ($@)"
+}
+
+function start() {
+    echo -en "Starting the daemon: "
     nohup "$installdir"/bin/maestro-inspector -m "$MAESTRO_BROKER" -i "$MAESTRO_INSPECTOR_CLASS" -l "$MAESTRO_LOG_DIR" $@ > /dev/null 2> /dev/null &
+    if [ $? -ne 0 ] ; then
+        eerror "failed to daemonize the Maestro inspector"
+        exit 1
+    fi
+
     sleep 2s
+    proc_count=0
     for pid in $(ps -ef | grep -i maestro-inspector | grep java | grep -v inspector-service | grep -v grep | awk ' { print $2 } ') ; do
-        echo "Maestro inspector started $pid"
+        if [ $proc_count -eq 0 ] ; then
+            esuccess
+        fi
+        echo -e "Maestro inspector started:$GREEN $pid $RESET"
     done
+
+    if [ $proc_count -eq 0 ] ; then
+        eerror "Maestro inspector did not start successfully"
+    fi
 }
 
 function stop() {
diff --git a/maestro-worker/src/main/scripts/maestro-worker-service b/maestro-worker/src/main/scripts/maestro-worker-service
--- a/maestro-worker/src/main/scripts/maestro-worker-service
+++ b/maestro-worker/src/main/scripts/maestro-worker-service
@@ -22,6 +22,18 @@ fi
 
 source "$installdir"/config/maestro-worker-service.conf
 
+RED="\e[0;31m"
+GREEN="\e[0;32m"
+RESET="\e[0m"
+
+function esuccess() {
+    echo -e "$GREEN OK$RESET"
+}
+
+function eerror() {
+    echo -e "$RED failed$RESET ($@)"
+}
+
 function start() {
     if [[ "$MAESTRO_WORKER_ROLE" == "sender" ]] ; then
         export MAESTRO_WORKER="$MAESTRO_SENDER_WORKER"
@@ -33,11 +45,26 @@ function start() {
         MAESTRO_LOCAL_HOSTNAME=$(hostname -f)
     fi
 
+    echo -en "Starting the $MAESTRO_WORKER_ROLE daemon: "
     nohup "$installdir"/bin/maestro-worker -m "$MAESTRO_BROKER" -w "$MAESTRO_WORKER" -l "$MAESTRO_LOG_DIR" -r "$MAESTRO_WORKER_ROLE" -H "$MAESTRO_LOCAL_HOSTNAME" $@ > /dev/null 2> /dev/null &
+    if [ $? -ne 0 ] ; then
+        eerror "failed to daemonize the Maestro worker"
+        exit 1
+    fi
+
     sleep 2s
+    proc_count=0
     for pid in $(ps -ef | grep -i maestro-worker | grep java | grep -v worker-service | grep -i "$MAESTRO_WORKER_ROLE"  | grep -v grep | awk ' { print $2 } ') ; do
-        echo "Maestro worker started $pid"
+        if [ $proc_count -eq 0 ] ; then
+            esuccess
+        fi
+        echo -e "Maestro worker started:$GREEN $pid $RESET"
+        ((proc_count++))
     done
+
+    if [ $proc_count -eq 0 ] ; then
+        eerror "Maestro agent did not start successfully"
+    fi
 }
 
 function stop() {
