FIX: ansible does not deal well w/ disown, therefore revert the start part

diff --git a/maestro-agent/src/main/scripts/maestro-agent-service b/maestro-agent/src/main/scripts/maestro-agent-service
--- a/maestro-agent/src/main/scripts/maestro-agent-service
+++ b/maestro-agent/src/main/scripts/maestro-agent-service
@@ -37,16 +37,28 @@ function eerror() {
 }
 
 function start() {
-    echo -en "Starting the daemon: "
-    "${installdir}/bin/maestro-agent" -m "${MAESTRO_BROKER}" -l "${MAESTRO_LOG_DIR}" "${@}" >/dev/null 2>/dev/null &
-    pid=$!
-    if ! kill -0 ${pid} ; then
-        eerror "Maestro agent did not start successfully"
+    echo -en "Starting the agent daemon: "
+    nohup "${installdir}/bin/maestro-agent" -m "${MAESTRO_BROKER}" -l "${MAESTRO_LOG_DIR}" "${@}" >/dev/null 2>/dev/null &
+    if [[ $? -ne 0 ]] ; then
+        eerror "failed to daemonize the Maestro agent"
         exit 1
     fi
-    disown ${pid}
-    echo -e "Maestro agent started:${GREEN} ${pid} ${RESET}"
+
+    sleep 1s
+    processCount=0
+    for pid in $(ps -ef | grep -i maestro-agent | grep java | grep -v grep | awk ' { print $2 } ') ; do
+        if [[ processCount -eq 0 ]] ; then
+            esuccess
+        fi
+        echo -e "Maestro agent started:${GREEN} ${pid} ${RESET}"
+        ((processCount++))
+    done
+
+    if [[ procCount -eq 0 ]] ; then
+        eerror "Maestro agent did not start successfully"
+    fi
 }
+
 
 function stop() {
     for pid in $(pgrep -f ".*java.*bin/maestro-agent.*") ; do
diff --git a/maestro-exporter/src/main/scripts/maestro-exporter-service b/maestro-exporter/src/main/scripts/maestro-exporter-service
--- a/maestro-exporter/src/main/scripts/maestro-exporter-service
+++ b/maestro-exporter/src/main/scripts/maestro-exporter-service
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #   Copyright 2017 Otavio Rodolfo Piske
 #
 #   Licensed under the Apache License, Version 2.0 (the "License");
@@ -37,15 +37,26 @@ function eerror() {
 }
 
 function start() {
-    echo -en "Starting the daemon: "
-    "${installdir}/bin/maestro-exporter" -m "${MAESTRO_BROKER}" "${@}" >/dev/null 2>/dev/null &
-    pid=$!
-    if ! kill -0 ${pid} ; then
-        eerror "Maestro exporter did not start successfully"
+    echo -en "Starting the exporter daemon: "
+    nohup "${installdir}/bin/maestro-exporter" -m "${MAESTRO_BROKER}" "${@}" >/dev/null 2>/dev/null &
+    if [[ $? -ne 0 ]] ; then
+        eerror "failed to daemonize the Maestro exporter"
         exit 1
     fi
-    disown ${pid}
-    echo -e "Maestro exporter started:${GREEN} ${pid} ${RESET}"
+
+    sleep 1s
+    processCount=0
+    for pid in $(ps -ef | grep -i maestro-exporter | grep java | grep -v grep | awk ' { print $2 } ') ; do
+        if [[ processCount -eq 0 ]] ; then
+            esuccess
+        fi
+        echo -e "Maestro exporter started:${GREEN} ${pid} ${RESET}"
+        ((processCount++))
+    done
+
+    if [[ procCount -eq 0 ]] ; then
+        eerror "Maestro exporter did not start successfully"
+    fi
 }
 
 function stop() {
diff --git a/maestro-worker/src/main/scripts/maestro-worker-service b/maestro-worker/src/main/scripts/maestro-worker-service
--- a/maestro-worker/src/main/scripts/maestro-worker-service
+++ b/maestro-worker/src/main/scripts/maestro-worker-service
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #   Copyright 2017 Otavio Rodolfo Piske
 #
 #   Licensed under the Apache License, Version 2.0 (the "License");
@@ -34,6 +34,33 @@ function esuccess() {
 
 function eerror() {
     echo -e "${RED} failed${RESET} ($@)"
+}
+
+function start() {
+    if [[ -z "$MAESTRO_LOCAL_HOSTNAME" ]] ; then
+        MAESTRO_LOCAL_HOSTNAME=$(hostname -f)
+    fi
+
+    echo -en "Starting the worker daemon: "
+    nohup "${installdir}"/bin/maestro-worker -m "$MAESTRO_BROKER" -l "$MAESTRO_LOG_DIR" -H "$MAESTRO_LOCAL_HOSTNAME" "$@" >/dev/null 2>/dev/null &
+    if [[ $? -ne 0 ]] ; then
+        eerror "failed to daemonize the Maestro worker"
+        exit 1
+    fi
+
+    sleep 1s
+    processCount=0
+    for pid in $(ps -ef | grep -i maestro-worker | grep java | grep -v worker-service | grep -v grep | awk ' { print $2 } ') ; do
+        if [[ processCount -eq 0 ]] ; then
+            esuccess
+        fi
+        echo -e "Maestro worker started:${GREEN} ${pid} ${RESET}"
+        ((processCount++))
+    done
+
+    if [[ procCount -eq 0 ]] ; then
+        eerror "Maestro agent did not start successfully"
+    fi
 }
 
 function start() {
